[package]
name = 'WICrowdfunding'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.WIFlagging2]
local = "../WI_Flagging"

[addresses]
std = "0x1"
testing = "0x815e0c554f2cdee0ff4e249727ba275952b30a09a11ba47d251a2fd2a5e28172"