[package]
name = 'WIFlagging'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
std = "0x1"
testing2 = "0xf9b87fdbdfda614b1aea4d5f695788cdb013241c7add0183c06cbbae29c1e99a"